### ISSUE TITLE
Outdated Python Plugin Framework documentation

### ISSUE THREAD

**Issue by 0xbb** [hexhex/core#14]
Hello!
I was trying to use dlvhex for a project. I am especially interested into your Python Plugin Framework.

While playing with it I noticed that the documentation on the homepage is outdated: http://www.kr.tuwien.ac.at/research/systems/dlvhex/doc2x/group__pythonpluginframework.html 

It seems that this issue was already fixed in the latest Git version.
Would it be possible to update the documentation on dlvhex's homepage? I think a more up to date documentation would be very useful for anyone starting using dlvhex. 

Greetings,
Bruno

**Comment by credl** [comment]
Dear Bruno!

You can generate an up-to-date documentation on your local system by
calling make doxygen.

We will update the online version with the next release. This is to make
sure that the doc coincides with the latest release rather than the current
development version; the latter is always subject to change.

Best,
Christoph
Am 18.05.2015 16:31 schrieb "Bruno Bierbaumer" <notifications@github.com>:

**Comment by 0xbb** [comment]
Hi Christoph,
yes I did so.
I just reported it, because the latest release is not working with online documentation, but with the current development one.

Greetings

**Comment by credl** [comment]
Dear Bruno!

Thanks for reporting!

Yes, there was also a small flaw in the documentation of 2.4. But uploading
the doc of the current development version would probably cause even more
confusion as it differs even more from what is implemented in 2.4; there
will be a new release in the next weeks anyway.

Best,
Christoph
Am 18.05.2015 17:00 schrieb "Bruno Bierbaumer" <notifications@github.com>:

**Comment by 0xbb** [comment]
Perfect, thank you for the really quick answer!
